# Welcome to Jekyll!
#

# Site settings
title: Les Bleus Vietnam
description: |
  Hội cổ động viên đội tuyển Pháp tại Việt Nam  
  |#FiersdetreBleus|
owner: Les Bleus Vietnam # or company name
first_published: 2014 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "franceteam.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/lesbleusvietnam
  #github: https://github.com/franceteam
  #linkedin-square: https://linkedin.com/in/lesbleus
  facebook-official: https://facebook.com/franceteamvn
  google-plus-square: https://plus.google.com/u/0/+lesbleusVN
  #email: lesbleus.vn@gmail.com
  #flickr:
  instagram: https://www.instagram.com/lesbleus.vn
  youtube-square: https://www.youtube.com/user/LesBleusVN
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
